spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/snap-local
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updated: true
    show-sql: true
  flyway:
    enabled: true
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

logging:
  level:
    org.springframework: INFO
    org.flyway: DEBUG